# config.toml

SAMPLE_ID = "inputs"
MAT_KEY = "C"

AMGX_DLL = "C:\\AMGX\\build\\Release\\amgxsh.dll"
# AMGX_DLL = raw"C:\Users\r43341mm\AMGX\build\Release\amgxsh.dll" # for my own computer

DIRECTION = 1

SPACING_X = 1.0
SPACING_Y = 1.0
SPACING_Z = 1.0

SSA_SIGMA = 0.0